# Create the preprocessor instance required for custom prediction on GCP AI Platform, requires the df.csv file generated by the jupyter notebook script

import pandas as pd
import numpy as np
import pickle
import preprocess


if __name__ == '__main__':
    df = pd.read_csv('df.csv', index_col=0)
    cols = list(df.drop(columns=['variety']).columns.array)
    ref_values = np.zeros(len(cols))

    pp_df = pd.DataFrame([ref_values], columns=cols).astype(int)
    pp = preprocess.AdjectiveColumnIndicators()
    pp._set_reference_df(pp_df)

    with open('preprocessor.pkl', 'wb') as f:
        pickle.dump(pp, f)
